"""ISO reference data for seeding (#1): ISO 4217 currencies + ISO 3166-1 countries.

Compact data so the seeder can load broad sets idempotently. Users can add more
via the UI. Currency: (code, symbol, decimals, name). Country: (iso2, iso3, name, ccy).
"""

# (code, symbol, decimals, name) — broad practical currency set.
ISO_CURRENCIES: list[tuple[str, str, int, str]] = [
    ("AED", "د.إ", 2, "UAE Dirham"), ("AFN", "؋", 2, "Afghan Afghani"), ("ALL", "L", 2, "Albanian Lek"),
    ("AMD", "֏", 2, "Armenian Dram"), ("ANG", "ƒ", 2, "Netherlands Antillean Guilder"), ("AOA", "Kz", 2, "Angolan Kwanza"),
    ("ARS", "$", 2, "Argentine Peso"), ("AUD", "$", 2, "Australian Dollar"), ("AWG", "ƒ", 2, "Aruban Florin"),
    ("AZN", "₼", 2, "Azerbaijani Manat"), ("BAM", "KM", 2, "Bosnia Convertible Mark"), ("BBD", "$", 2, "Barbadian Dollar"),
    ("BDT", "৳", 2, "Bangladeshi Taka"), ("BGN", "лв", 2, "Bulgarian Lev"), ("BHD", ".د.ب", 3, "Bahraini Dinar"),
    ("BIF", "FBu", 0, "Burundian Franc"), ("BMD", "$", 2, "Bermudian Dollar"), ("BND", "$", 2, "Brunei Dollar"),
    ("BOB", "Bs.", 2, "Bolivian Boliviano"), ("BRL", "R$", 2, "Brazilian Real"), ("BSD", "$", 2, "Bahamian Dollar"),
    ("BTN", "Nu.", 2, "Bhutanese Ngultrum"), ("BWP", "P", 2, "Botswanan Pula"), ("BYN", "Br", 2, "Belarusian Ruble"),
    ("BZD", "$", 2, "Belize Dollar"), ("CAD", "$", 2, "Canadian Dollar"), ("CDF", "FC", 2, "Congolese Franc"),
    ("CHF", "CHF", 2, "Swiss Franc"), ("CLP", "$", 0, "Chilean Peso"), ("CNY", "¥", 2, "Chinese Yuan"),
    ("COP", "$", 2, "Colombian Peso"), ("CRC", "₡", 2, "Costa Rican Colón"), ("CUP", "$", 2, "Cuban Peso"),
    ("CVE", "$", 2, "Cape Verdean Escudo"), ("CZK", "Kč", 2, "Czech Koruna"), ("DJF", "Fdj", 0, "Djiboutian Franc"),
    ("DKK", "kr", 2, "Danish Krone"), ("DOP", "RD$", 2, "Dominican Peso"), ("DZD", "دج", 2, "Algerian Dinar"),
    ("EGP", "£", 2, "Egyptian Pound"), ("ERN", "Nfk", 2, "Eritrean Nakfa"), ("ETB", "Br", 2, "Ethiopian Birr"),
    ("EUR", "€", 2, "Euro"), ("FJD", "$", 2, "Fijian Dollar"), ("GBP", "£", 2, "British Pound"),
    ("GEL", "₾", 2, "Georgian Lari"), ("GHS", "₵", 2, "Ghanaian Cedi"), ("GMD", "D", 2, "Gambian Dalasi"),
    ("GNF", "FG", 0, "Guinean Franc"), ("GTQ", "Q", 2, "Guatemalan Quetzal"), ("HKD", "$", 2, "Hong Kong Dollar"),
    ("HNL", "L", 2, "Honduran Lempira"), ("HRK", "kn", 2, "Croatian Kuna"), ("HTG", "G", 2, "Haitian Gourde"),
    ("HUF", "Ft", 2, "Hungarian Forint"), ("IDR", "Rp", 2, "Indonesian Rupiah"), ("ILS", "₪", 2, "Israeli New Shekel"),
    ("INR", "₹", 2, "Indian Rupee"), ("IQD", "ع.د", 3, "Iraqi Dinar"), ("IRR", "﷼", 2, "Iranian Rial"),
    ("ISK", "kr", 0, "Icelandic Króna"), ("JMD", "$", 2, "Jamaican Dollar"), ("JOD", "د.ا", 3, "Jordanian Dinar"),
    ("JPY", "¥", 0, "Japanese Yen"), ("KES", "KSh", 2, "Kenyan Shilling"), ("KGS", "с", 2, "Kyrgystani Som"),
    ("KHR", "៛", 2, "Cambodian Riel"), ("KRW", "₩", 0, "South Korean Won"), ("KWD", "د.ك", 3, "Kuwaiti Dinar"),
    ("KZT", "₸", 2, "Kazakhstani Tenge"), ("LAK", "₭", 2, "Laotian Kip"), ("LBP", "ل.ل", 2, "Lebanese Pound"),
    ("LKR", "Rs", 2, "Sri Lankan Rupee"), ("LYD", "ل.د", 3, "Libyan Dinar"), ("MAD", "د.م.", 2, "Moroccan Dirham"),
    ("MDL", "L", 2, "Moldovan Leu"), ("MGA", "Ar", 2, "Malagasy Ariary"), ("MKD", "ден", 2, "Macedonian Denar"),
    ("MMK", "K", 2, "Myanmar Kyat"), ("MNT", "₮", 2, "Mongolian Tugrik"), ("MOP", "MOP$", 2, "Macanese Pataca"),
    ("MUR", "₨", 2, "Mauritian Rupee"), ("MVR", "Rf", 2, "Maldivian Rufiyaa"), ("MWK", "MK", 2, "Malawian Kwacha"),
    ("MXN", "$", 2, "Mexican Peso"), ("MYR", "RM", 2, "Malaysian Ringgit"), ("MZN", "MT", 2, "Mozambican Metical"),
    ("NAD", "$", 2, "Namibian Dollar"), ("NGN", "₦", 2, "Nigerian Naira"), ("NOK", "kr", 2, "Norwegian Krone"),
    ("NPR", "₨", 2, "Nepalese Rupee"), ("NZD", "$", 2, "New Zealand Dollar"), ("OMR", "ر.ع.", 3, "Omani Rial"),
    ("PAB", "B/.", 2, "Panamanian Balboa"), ("PEN", "S/", 2, "Peruvian Sol"), ("PHP", "₱", 2, "Philippine Peso"),
    ("PKR", "₨", 2, "Pakistani Rupee"), ("PLN", "zł", 2, "Polish Zloty"), ("PYG", "₲", 0, "Paraguayan Guarani"),
    ("QAR", "ر.ق", 2, "Qatari Rial"), ("RON", "lei", 2, "Romanian Leu"), ("RSD", "дин.", 2, "Serbian Dinar"),
    ("RUB", "₽", 2, "Russian Ruble"), ("RWF", "FRw", 0, "Rwandan Franc"), ("SAR", "﷼", 2, "Saudi Riyal"),
    ("SCR", "₨", 2, "Seychellois Rupee"), ("SDG", "ج.س.", 2, "Sudanese Pound"), ("SEK", "kr", 2, "Swedish Krona"),
    ("SGD", "$", 2, "Singapore Dollar"), ("SOS", "S", 2, "Somali Shilling"), ("SYP", "£", 2, "Syrian Pound"),
    ("THB", "฿", 2, "Thai Baht"), ("TJS", "ЅМ", 2, "Tajikistani Somoni"), ("TMT", "m", 2, "Turkmenistani Manat"),
    ("TND", "د.ت", 3, "Tunisian Dinar"), ("TRY", "₺", 2, "Turkish Lira"), ("TTD", "$", 2, "Trinidad Dollar"),
    ("TWD", "NT$", 2, "New Taiwan Dollar"), ("TZS", "TSh", 2, "Tanzanian Shilling"), ("UAH", "₴", 2, "Ukrainian Hryvnia"),
    ("UGX", "USh", 0, "Ugandan Shilling"), ("USD", "$", 2, "US Dollar"), ("UYU", "$U", 2, "Uruguayan Peso"),
    ("UZS", "so'm", 2, "Uzbekistani Som"), ("VND", "₫", 0, "Vietnamese Dong"), ("XAF", "FCFA", 0, "Central African CFA Franc"),
    ("XOF", "CFA", 0, "West African CFA Franc"), ("YER", "﷼", 2, "Yemeni Rial"), ("ZAR", "R", 2, "South African Rand"),
    ("ZMW", "ZK", 2, "Zambian Kwacha"), ("ZWL", "$", 2, "Zimbabwean Dollar"), ("BTC", "₿", 8, "Bitcoin"),
]

# (iso2, iso3, name, default_currency)
ISO_COUNTRIES: list[tuple[str, str, str, str | None]] = [
    ("AE", "ARE", "United Arab Emirates", "AED"), ("AF", "AFG", "Afghanistan", "AFN"), ("AL", "ALB", "Albania", "ALL"),
    ("AM", "ARM", "Armenia", "AMD"), ("AO", "AGO", "Angola", "AOA"), ("AR", "ARG", "Argentina", "ARS"),
    ("AT", "AUT", "Austria", "EUR"), ("AU", "AUS", "Australia", "AUD"), ("AZ", "AZE", "Azerbaijan", "AZN"),
    ("BA", "BIH", "Bosnia and Herzegovina", "BAM"), ("BD", "BGD", "Bangladesh", "BDT"), ("BE", "BEL", "Belgium", "EUR"),
    ("BG", "BGR", "Bulgaria", "BGN"), ("BH", "BHR", "Bahrain", "BHD"), ("BR", "BRA", "Brazil", "BRL"),
    ("BY", "BLR", "Belarus", "BYN"), ("CA", "CAN", "Canada", "CAD"), ("CH", "CHE", "Switzerland", "CHF"),
    ("CL", "CHL", "Chile", "CLP"), ("CN", "CHN", "China", "CNY"), ("CO", "COL", "Colombia", "COP"),
    ("CZ", "CZE", "Czechia", "CZK"), ("DE", "DEU", "Germany", "EUR"), ("DK", "DNK", "Denmark", "DKK"),
    ("DZ", "DZA", "Algeria", "DZD"), ("EG", "EGY", "Egypt", "EGP"), ("ES", "ESP", "Spain", "EUR"),
    ("ET", "ETH", "Ethiopia", "ETB"), ("FI", "FIN", "Finland", "EUR"), ("FR", "FRA", "France", "EUR"),
    ("GB", "GBR", "United Kingdom", "GBP"), ("GE", "GEO", "Georgia", "GEL"), ("GH", "GHA", "Ghana", "GHS"),
    ("GR", "GRC", "Greece", "EUR"), ("HK", "HKG", "Hong Kong", "HKD"), ("HR", "HRV", "Croatia", "EUR"),
    ("HU", "HUN", "Hungary", "HUF"), ("ID", "IDN", "Indonesia", "IDR"), ("IE", "IRL", "Ireland", "EUR"),
    ("IL", "ISR", "Israel", "ILS"), ("IN", "IND", "India", "INR"), ("IQ", "IRQ", "Iraq", "IQD"),
    ("IR", "IRN", "Iran", "IRR"), ("IS", "ISL", "Iceland", "ISK"), ("IT", "ITA", "Italy", "EUR"),
    ("JO", "JOR", "Jordan", "JOD"), ("JP", "JPN", "Japan", "JPY"), ("KE", "KEN", "Kenya", "KES"),
    ("KR", "KOR", "South Korea", "KRW"), ("KW", "KWT", "Kuwait", "KWD"), ("KZ", "KAZ", "Kazakhstan", "KZT"),
    ("LB", "LBN", "Lebanon", "LBP"), ("LK", "LKA", "Sri Lanka", "LKR"), ("LU", "LUX", "Luxembourg", "EUR"),
    ("MA", "MAR", "Morocco", "MAD"), ("MX", "MEX", "Mexico", "MXN"), ("MY", "MYS", "Malaysia", "MYR"),
    ("NG", "NGA", "Nigeria", "NGN"), ("NL", "NLD", "Netherlands", "EUR"), ("NO", "NOR", "Norway", "NOK"),
    ("NP", "NPL", "Nepal", "NPR"), ("NZ", "NZL", "New Zealand", "NZD"), ("OM", "OMN", "Oman", "OMR"),
    ("PE", "PER", "Peru", "PEN"), ("PH", "PHL", "Philippines", "PHP"), ("PK", "PAK", "Pakistan", "PKR"),
    ("PL", "POL", "Poland", "PLN"), ("PT", "PRT", "Portugal", "EUR"), ("QA", "QAT", "Qatar", "QAR"),
    ("RO", "ROU", "Romania", "RON"), ("RS", "SRB", "Serbia", "RSD"), ("RU", "RUS", "Russia", "RUB"),
    ("SA", "SAU", "Saudi Arabia", "SAR"), ("SE", "SWE", "Sweden", "SEK"), ("SG", "SGP", "Singapore", "SGD"),
    ("TH", "THA", "Thailand", "THB"), ("TN", "TUN", "Tunisia", "TND"), ("TR", "TUR", "Türkiye", "TRY"),
    ("TW", "TWN", "Taiwan", "TWD"), ("TZ", "TZA", "Tanzania", "TZS"), ("UA", "UKR", "Ukraine", "UAH"),
    ("UG", "UGA", "Uganda", "UGX"), ("US", "USA", "United States", "USD"), ("UY", "URY", "Uruguay", "UYU"),
    ("UZ", "UZB", "Uzbekistan", "UZS"), ("VN", "VNM", "Vietnam", "VND"), ("YE", "YEM", "Yemen", "YER"),
    ("ZA", "ZAF", "South Africa", "ZAR"), ("ZM", "ZMB", "Zambia", "ZMW"), ("ZW", "ZWE", "Zimbabwe", "ZWL"),
]
